name: release

on: 
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      #  checkout step so project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v2.3.1
      # Ensure that you get the entire project history
      with:
        fetch-depth: 0
    - name: export game
      uses: firebelley/godot-export@v2.8.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.3/rc9/Godot_v3.3-rc9_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.3/rc9/Godot_v3.3-rc9_export_templates.tpz
        relative_project_path: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
